name: architecture
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  binder:
    path: ../../packages/binder
  characters: ^1.0.0
  cupertino_icons: ^1.0.0
  freezed_annotation: ^0.12.0
  gap: ^1.2.0
  http: ^0.12.2
  shared_preferences: ^0.5.12+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  freezed: ^0.12.2
  json_serializable: ^3.5.0
  mockito: ^4.1.2

flutter:
  uses-material-design: true
