name: Build

on:
  push:
  pull_request:

jobs:
  sanity_check:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        package:
          - packages/binder
          - examples/architecture
          - examples/counter
          - examples/select
          - examples/todos
          - examples/undo_redo
          - examples/users_devices
        channel:
          - stable
          - dev
          - beta
          - master

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Removing example folder
        run: rm -rf example
        working-directory: ${{ matrix.package }}

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ matrix.package }}

      - name: Check format
        run: flutter format --set-exit-if-changed .
        working-directory: ${{ matrix.package }}

      - name: Analyze
        run: flutter analyze
        working-directory: ${{ matrix.package }}

      - name: Run tests
        run: flutter test --coverage
        working-directory: ${{ matrix.package }}